/**
 Implementacion ventana preferencias.
*/

#include "gui.h"
#include "prefs.h"


// Implementacion

FXIMPLEMENT(dlgPrefs, FXDialogBox,NULL,0)


// Constructor

dlgPrefs::dlgPrefs(guiWindow *owner):FXDialogBox(owner,"Cambiar colores",DECOR_TITLE
	|DECOR_BORDER|DECOR_RESIZE,0,0,0,0, 0,0,0,0, 4,4) {

	FXVerticalFrame  *vert = new FXVerticalFrame(this,LAYOUT_SIDE_TOP|LAYOUT_FILL_X
		|LAYOUT_FILL_Y);


	// Libro de Pestañas para elegir componente de la GUI

	FXTabBook *prefsTB = new FXTabBook(vert, NULL,0
		,PACK_UNIFORM_WIDTH|PACK_UNIFORM_HEIGHT
		|LAYOUT_FILL_X|LAYOUT_FILL_Y|LAYOUT_RIGHT);

	///////////////		Pestaña de la TABLA DE SIMBOLOS

	FXTabItem *tabTS = new FXTabItem(prefsTB, "Tabla de simbolos", NULL);

	// Colores para la TABLA DE SIMBOLOS

	FXMatrix *matrix1=new FXMatrix(prefsTB, 7, MATRIX_BY_ROWS|PACK_UNIFORM_HEIGHT
		|LAYOUT_FILL_X|LAYOUT_FILL_Y|FRAME_THICK|FRAME_RAISED
		,0,0,0,0, 4,4,4,4, 4, 4);

	new FXLabel(matrix1, "Normal FG:", NULL, JUSTIFY_LEFT|LAYOUT_CENTER_Y
		|LAYOUT_FILL_ROW|LAYOUT_FILL_X);
	new FXLabel(matrix1, "Nuevo simbolo FG:", NULL, JUSTIFY_LEFT|LAYOUT_CENTER_Y
		|LAYOUT_FILL_ROW|LAYOUT_FILL_X);
	new FXLabel(matrix1, "Simbolo encontrado FG:", NULL
		, JUSTIFY_LEFT|LAYOUT_CENTER_Y|LAYOUT_FILL_ROW|LAYOUT_FILL_X);
	new FXLabel(matrix1, "Procedimiento encontrado FG:", NULL
		, JUSTIFY_LEFT|LAYOUT_CENTER_Y|LAYOUT_FILL_ROW|LAYOUT_FILL_X);
	new FXLabel(matrix1, "Parametro encontrado FG:", NULL
		, JUSTIFY_LEFT|LAYOUT_CENTER_Y|LAYOUT_FILL_ROW|LAYOUT_FILL_X);
	new FXLabel(matrix1, "Simbolos a eliminar FG:", NULL
		, JUSTIFY_LEFT|LAYOUT_CENTER_Y|LAYOUT_FILL_ROW|LAYOUT_FILL_X);

	new FXLabel(matrix1, "Simbolo duplicado FG:", NULL
		, JUSTIFY_LEFT|LAYOUT_CENTER_Y|LAYOUT_FILL_ROW|LAYOUT_FILL_X);
		
	// Normal FG
	new FXColorWell(matrix1,FXRGB(0,0,0),owner, guiWindow::ID_TAB_FG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);
	
	// Nuevo FG
	new FXColorWell(matrix1,FXRGB(155,155,155), owner, guiWindow::ID_TAB_NEW_FG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	// Sim encontrado FG
	new FXColorWell(matrix1,FXRGB(155,155,155), owner, guiWindow::ID_TAB_SIM_FG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	// Proc encontrado
	new FXColorWell(matrix1,FXRGB(155,155,155), owner, guiWindow::ID_TAB_PROC_FG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	// Param encontrado
	new FXColorWell(matrix1,FXRGB(155,155,155), owner, guiWindow::ID_TAB_PARAM_FG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	// A eliminar
	new FXColorWell(matrix1,FXRGB(155,155,155), owner, guiWindow::ID_TAB_DEL_FG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	// Simbolo duplicado
	new FXColorWell(matrix1,FXRGB(155,155,155), owner, guiWindow::ID_TAB_DUP_FG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);


	new FXLabel(matrix1, "Normal BG:", NULL, JUSTIFY_LEFT|LAYOUT_CENTER_Y
		|LAYOUT_FILL_ROW|LAYOUT_FILL_X);

	new FXLabel(matrix1, "Nuevo simbolo BG:", NULL, JUSTIFY_LEFT|LAYOUT_CENTER_Y
		|LAYOUT_FILL_ROW|LAYOUT_FILL_X);
	new FXLabel(matrix1, "Simbolo encontrado BG:", NULL
		, JUSTIFY_LEFT|LAYOUT_CENTER_Y|LAYOUT_FILL_ROW|LAYOUT_FILL_X);
	new FXLabel(matrix1, "Procedimiento encontrado BG:", NULL
		, JUSTIFY_LEFT|LAYOUT_CENTER_Y|LAYOUT_FILL_ROW|LAYOUT_FILL_X);
	new FXLabel(matrix1, "Parametro encontrado BG:", NULL
		, JUSTIFY_LEFT|LAYOUT_CENTER_Y|LAYOUT_FILL_ROW|LAYOUT_FILL_X);
	new FXLabel(matrix1, "Simbolos a eliminar BG:", NULL
		, JUSTIFY_LEFT|LAYOUT_CENTER_Y|LAYOUT_FILL_ROW|LAYOUT_FILL_X);
	new FXLabel(matrix1, "Simbolos duplicado BG:", NULL
		, JUSTIFY_LEFT|LAYOUT_CENTER_Y|LAYOUT_FILL_ROW|LAYOUT_FILL_X);


	// Normal Fondo
	new FXColorWell(matrix1,FXRGB(255,255,255),owner, guiWindow::ID_TAB_BG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	// Nuevo Fondo
	new FXColorWell(matrix1,FXRGB(255,255,255),owner, guiWindow::ID_TAB_NEW_BG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	// Sim encontrado Fondo
	new FXColorWell(matrix1,FXRGB(255,255,255), owner, guiWindow::ID_TAB_SIM_BG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	// Proc encontrado Fondo
	new FXColorWell(matrix1,FXRGB(255,255,255), owner, guiWindow::ID_TAB_PROC_BG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	// Param encontrado Fondo
	new FXColorWell(matrix1,FXRGB(255,255,255), owner, guiWindow::ID_TAB_PARAM_BG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	// A eliminar Fondo
	new FXColorWell(matrix1,FXRGB(255,255,255), owner, guiWindow::ID_TAB_DEL_BG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	// Simbolo duplicado Fondo
	new FXColorWell(matrix1,FXRGB(255,255,255), owner, guiWindow::ID_TAB_DUP_BG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);


	//////////////		Pesta�a para el CODIGO FUENTE

	FXTabItem *tabCOD = new FXTabItem(prefsTB, "Codigo Fuente", NULL);

	FXMatrix *matrix2=new FXMatrix(prefsTB,4,MATRIX_BY_ROWS|PACK_UNIFORM_HEIGHT
		|LAYOUT_FILL_X|LAYOUT_FILL_Y|FRAME_THICK|FRAME_RAISED
		,0,0,0,0, 4,4,4,4, 4, 4);

	// Colores de frente
	new FXLabel(matrix2, "Texto FG:", NULL, JUSTIFY_LEFT|LAYOUT_CENTER_Y
		|LAYOUT_FILL_ROW|LAYOUT_FILL_X);

	new FXLabel(matrix2, "Texto activo FG:", NULL, JUSTIFY_LEFT|LAYOUT_CENTER_Y
		|LAYOUT_FILL_ROW|LAYOUT_FILL_X);

	new FXLabel(matrix2, "Texto error FG:", NULL, JUSTIFY_LEFT|LAYOUT_CENTER_Y
		|LAYOUT_FILL_ROW|LAYOUT_FILL_X);

	new FXLabel(matrix2, "Numeros de linea FG:", NULL, JUSTIFY_LEFT|LAYOUT_CENTER_Y
		|LAYOUT_FILL_ROW|LAYOUT_FILL_X);

	new FXColorWell(matrix2,FXRGB(0,0,0),owner, guiWindow::ID_COD_FG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	new FXColorWell(matrix2,FXRGB(255,255,255), owner, guiWindow::ID_COD_SEL_FG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	new FXColorWell(matrix2,FXRGB(255,255,255), owner, guiWindow::ID_COD_ERR_FG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	new FXColorWell(matrix2,FXRGB(0,0,0), owner, guiWindow::ID_COD_NLIN_FG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	// Relleno
	new FXFrame(matrix2, LAYOUT_FILL_COLUMN|LAYOUT_FILL_ROW);
	new FXFrame(matrix2, LAYOUT_FILL_COLUMN|LAYOUT_FILL_ROW);
	new FXFrame(matrix2, LAYOUT_FILL_COLUMN|LAYOUT_FILL_ROW);
	new FXFrame(matrix2, LAYOUT_FILL_COLUMN|LAYOUT_FILL_ROW);

	// Colores fondo
	new FXLabel(matrix2, "Texto BG:", NULL, JUSTIFY_LEFT|LAYOUT_CENTER_Y
		|LAYOUT_FILL_ROW|LAYOUT_FILL_X);
	new FXLabel(matrix2, "Texto activo BG:", NULL, JUSTIFY_LEFT|LAYOUT_CENTER_Y
		|LAYOUT_FILL_ROW|LAYOUT_FILL_X);
	new FXLabel(matrix2, "Texto error BG:", NULL, JUSTIFY_LEFT|LAYOUT_CENTER_Y
		|LAYOUT_FILL_ROW|LAYOUT_FILL_X);
	new FXLabel(matrix2, "Numeros de linea BG:", NULL, JUSTIFY_LEFT|LAYOUT_CENTER_Y
		|LAYOUT_FILL_ROW|LAYOUT_FILL_X);


	new FXColorWell(matrix2,FXRGB(255,255,255),owner, guiWindow::ID_COD_BG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	new FXColorWell(matrix2,FXRGB(25,25,255), owner, guiWindow::ID_COD_SEL_BG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	new FXColorWell(matrix2,FXRGB(25,25,255), owner, guiWindow::ID_COD_ERR_BG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	new FXColorWell(matrix2,FXRGB(200,200,225), owner, guiWindow::ID_COD_NLIN_BG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);


	//////////////		Pestaña para colores GRAMATICA

	FXTabItem *tabGRAM = new FXTabItem(prefsTB, "Gramatica", NULL);

	FXMatrix *matrix3=new FXMatrix(prefsTB,4,MATRIX_BY_ROWS|PACK_UNIFORM_HEIGHT
		|LAYOUT_FILL_X|LAYOUT_FILL_Y|FRAME_THICK|FRAME_RAISED
		,0,0,0,0, 4,4,4,4, 4, 4);

	new FXLabel(matrix3, "Texto FG:", NULL, JUSTIFY_LEFT|LAYOUT_CENTER_Y
		|LAYOUT_FILL_ROW|LAYOUT_FILL_X);
	new FXLabel(matrix3, "Texto BG:", NULL, JUSTIFY_LEFT|LAYOUT_CENTER_Y
		|LAYOUT_FILL_ROW|LAYOUT_FILL_X);

	new FXLabel(matrix3, "Texto activo FG:", NULL, JUSTIFY_LEFT|LAYOUT_CENTER_Y
		|LAYOUT_FILL_ROW|LAYOUT_FILL_X);
	new FXLabel(matrix3, "Texto activo BG:", NULL, JUSTIFY_LEFT|LAYOUT_CENTER_Y
		|LAYOUT_FILL_ROW|LAYOUT_FILL_X);


	new FXColorWell(matrix3,FXRGB(0,0,0),owner, guiWindow::ID_GRAM_FG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	new FXColorWell(matrix3,FXRGB(255,255,255),owner, guiWindow::ID_GRAM_BG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	new FXColorWell(matrix3,FXRGB(255,15,15), owner, guiWindow::ID_GRAM_ACT_FG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	new FXColorWell(matrix3,FXRGB(255,255,255), owner, guiWindow::ID_GRAM_ACT_BG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);


	//////////////		Pestaña para colores CODIGO GENERADO

	FXTabItem *tabGEN = new FXTabItem(prefsTB, "Codigo generado", NULL);

	FXMatrix *matrix4=new FXMatrix(prefsTB,2,MATRIX_BY_ROWS|PACK_UNIFORM_HEIGHT
		|LAYOUT_FILL_X|LAYOUT_FILL_Y|FRAME_THICK|FRAME_RAISED
		,0,0,0,0, 4,4,4,4, 4, 4);

	new FXLabel(matrix4, "Texto FG:", NULL, JUSTIFY_LEFT|LAYOUT_CENTER_Y
		|LAYOUT_FILL_ROW|LAYOUT_FILL_X);
	new FXLabel(matrix4, "Texto BG:", NULL, JUSTIFY_LEFT|LAYOUT_CENTER_Y
		|LAYOUT_FILL_ROW|LAYOUT_FILL_X);


	new FXColorWell(matrix4,FXRGB(0,0,0),owner, guiWindow::ID_GEN_FG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);

	new FXColorWell(matrix4,FXRGB(255,255,255),owner, guiWindow::ID_GEN_BG
		,FRAME_SUNKEN|FRAME_THICK
		|LAYOUT_LEFT|LAYOUT_CENTER_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT
		|LAYOUT_FILL_ROW,0,0,40,24);


	// Botones Aceptar/Rechazar
	new FXHorizontalSeparator(vert,SEPARATOR_RIDGE|LAYOUT_FILL_X);
	FXHorizontalFrame *closebox = new FXHorizontalFrame(vert
		,LAYOUT_BOTTOM|LAYOUT_FILL_X|PACK_UNIFORM_WIDTH);

	new FXButton(closebox,"&Aceptar",NULL,this,FXDialogBox::ID_ACCEPT,BUTTON_INITIAL
		|BUTTON_DEFAULT|LAYOUT_RIGHT|FRAME_RAISED|FRAME_THICK,0,0,0,0, 20,20);
	new FXButton(closebox,"&Cancelar",NULL,this,FXDialogBox::ID_CANCEL,BUTTON_DEFAULT
		|LAYOUT_RIGHT|FRAME_RAISED|FRAME_THICK,0,0,0,0, 20,20);

	}



		

